# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b20cc9fa1fcc52c07cbe2d63a0dea701168e759d0dd2cea2b30af4c903efe7519cb421f76a706039ee5a391486f26583758094a22cbce586c76088881b9b9d2

test:
  secret_key_base: 03a2569ca5e56baa738fd9b8940761566a909231f38006423b7a6f48918f019b271558bb1081a8ea6aa1069eacf9a3c3fe8eba489d16c8078e5f7e231cf85170

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
